### ISSUE TITLE
Module breaks matplotlib

### ISSUE THREAD

**Issue by bollenn** [Crimson-Crow/json-numpy#2]
Using this module patch functionality together with `matplotlib` results in errors in the later.

See PR https://github.com/matplotlib/matplotlib/pull/28528.

It would be good to find an alternative approach for overwriting the `default` function.

**Comment by Crimson-Crow** [comment]
Looking into it. Indeed the `json_numpy` module is not cooperating with modules requiring custom encoding, and I could foresee that same problem happening with decoding as well (with `object_hook`).
